# Generated by Django 4.2.11 on 2026-06-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_walletvoucher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerrating',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='currency',
            field=models.CharField(default='MAD', max_length=8),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('topup', 'Top-up'), ('payment', 'Payment'), ('refund', 'Refund'), ('bonus', 'Bonus'), ('loyalty', 'Loyalty redemption')], max_length=20),
        ),
    ]
