# Generated by Django 4.2.11 on 2026-06-02 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_customerrating_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantFloatTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(db_index=True)),
                ('type', models.CharField(choices=[('fund', 'Platform funding'), ('distribution', 'Client top-up'), ('reversal', 'Reversal')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actor_user_id', models.IntegerField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('currency', models.CharField(default='MAD', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_float', to='accounts.customer')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
