# Generated by Django 4.2.11 on 2026-06-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_tenantfloattransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('topup', 'Top-up'), ('payment', 'Payment'), ('refund', 'Refund'), ('bonus', 'Bonus'), ('loyalty', 'Loyalty redemption'), ('transfer_out', 'Transfer sent'), ('transfer_in', 'Transfer received')], max_length=20),
        ),
    ]
