# Generated by Django 4.2.11 on 2026-06-02 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_wallettransaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrderRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(db_index=True)),
                ('restaurant_name', models.CharField(blank=True, max_length=200)),
                ('restaurant_slug', models.CharField(blank=True, max_length=200)),
                ('order_number', models.CharField(max_length=20)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('fulfillment_type', models.CharField(blank=True, max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='MAD', max_length=8)),
                ('order_created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_refs', to='accounts.customer')),
            ],
            options={
                'ordering': ('-order_created_at',),
                'indexes': [models.Index(fields=['customer', '-order_created_at'], name='order_ref_customer_recent_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='customerorderref',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'order_number'), name='uniq_order_ref_per_tenant_order'),
        ),
    ]
