# Generated by Django 4.2.11 on 2026-06-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_customerorderref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderref',
            name='items_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
