# Generated by Django 4.2.11 on 2026-06-03 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_customerorderref_items_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Bank transfer')], default='cash', max_length=16)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('idempotency_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('actor_user_id', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='MAD', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='accounts.customer')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
