# Generated by Django 4.2.11 on 2026-06-03 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_driverpayout'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletChargeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(db_index=True)),
                ('restaurant_name', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='MAD', max_length=8)),
                ('order_number', models.CharField(blank=True, max_length=100)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('charged', 'Charged'), ('declined', 'Declined'), ('expired', 'Expired')], db_index=True, default='pending', max_length=12)),
                ('idempotency_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('actor_user_id', models.IntegerField(blank=True, null=True)),
                ('wallet_tx_id', models.IntegerField(blank=True, null=True)),
                ('bill_synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_requests', to='accounts.customer')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['customer', 'status'], name='charge_req_customer_status_idx')],
            },
        ),
    ]
