# Generated by Django 4.2.11 on 2026-06-03 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_platformconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True)),
                ('p256dh', models.TextField(help_text='Client public key (URL-safe base64)')),
                ('auth', models.CharField(help_text='Auth secret (URL-safe base64)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='accounts.customer')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
