# Generated by Django 4.2.11 on 2026-06-05 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_customer_driver_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('push', 'Web Push'), ('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], db_index=True, max_length=12)),
                ('event', models.CharField(blank=True, help_text='e.g. order.new, order.ready, review_prompt, driver.dispatch', max_length=40)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, max_length=10)),
                ('recipient', models.CharField(blank=True, help_text='Phone / email / subscriber count — never sensitive payload.', max_length=120)),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('reference', models.CharField(blank=True, db_index=True, help_text='Related order number, if any.', max_length=40)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('tenant_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['tenant_id', 'created_at'], name='accounts_no_tenant__169a39_idx'), models.Index(fields=['channel', 'status'], name='accounts_no_channel_bf0c64_idx')],
            },
        ),
    ]
