# Generated by Django 4.2.11 on 2026-06-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_notificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='notify_order_updates',
            field=models.BooleanField(default=True, help_text='Receive order status updates by email/SMS (e.g. confirmed, ready).'),
        ),
        migrations.AddField(
            model_name='customer',
            name='notify_review_prompts',
            field=models.BooleanField(default=True, help_text="Receive the post-order 'rate your order' reminder push."),
        ),
    ]
