# Generated by Django 4.2.11 on 2026-06-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_customer_notify_order_updates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('topup', 'Top-up'), ('payment', 'Payment'), ('refund', 'Refund'), ('bonus', 'Bonus'), ('loyalty', 'Loyalty redemption'), ('transfer_out', 'Transfer sent'), ('transfer_in', 'Transfer received'), ('adjustment', 'Adjustment'), ('earning', 'Delivery earning'), ('cashout', 'Cash-out')], max_length=20),
        ),
    ]
