# Generated by Django 4.2.11 on 2026-06-05 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_wallettransaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverCashoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='MAD', max_length=8)),
                ('code', models.CharField(db_index=True, help_text='Short code the driver shows the restaurant.', max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='pending', max_length=12)),
                ('tenant_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('actor_user_id', models.IntegerField(blank=True, null=True)),
                ('wallet_tx_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashout_requests', to='accounts.customer')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'expires_at'], name='accounts_dr_status_c12351_idx')],
            },
        ),
    ]
