# Generated by Django 4.2.11 on 2026-06-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_drivercashoutrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryjob',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryjob',
            name='code_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deliveryjob',
            name='code_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryjob',
            name='failure_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='deliveryjob',
            name='failure_reason',
            field=models.CharField(blank=True, choices=[('customer_no_show', 'Customer not reachable / no-show'), ('bad_address', 'Address wrong or not found'), ('driver_unable', 'Driver unable (vehicle, accident…)'), ('other', 'Other')], help_text='Why the driver marked this delivery failed.', max_length=20),
        ),
        migrations.AddField(
            model_name='deliveryjob',
            name='owner_alerted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryjob',
            name='redispatch_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deliveryjob',
            name='resolution',
            field=models.CharField(blank=True, choices=[('redispatched', 'Re-dispatched'), ('refunded_cancelled', 'Refunded & cancelled'), ('noshow_paid', 'Driver paid (no-show)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='deliveryjob',
            name='status',
            field=models.CharField(choices=[('searching', 'Searching for driver'), ('assigned', 'Driver assigned'), ('at_restaurant', 'At restaurant'), ('picked_up', 'Picked up'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='searching', max_length=20),
        ),
        migrations.AddIndex(
            model_name='deliveryjob',
            index=models.Index(fields=['status', 'owner_alerted_at'], name='accounts_de_status_5c8c78_idx'),
        ),
    ]
