# Generated by Django 4.2.11 on 2026-06-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_deliveryjob_cancelled_at_deliveryjob_code_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryjob',
            name='platform_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
