# Generated by Django 4.2.11 on 2026-06-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_deliveryjob_platform_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryjob',
            name='food_ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
