# Generated by Django 4.2.11 on 2026-06-08 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_deliveryjob_food_ready_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryjob',
            name='declined_by',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='deliveryjob',
            name='is_open_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryjob',
            name='offer_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryjob',
            name='offer_round',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deliveryjob',
            name='offered_to',
            field=models.ForeignKey(blank=True, help_text='Driver currently holding the exclusive offer (None once open to the pool).', limit_choices_to={'is_driver': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offered_delivery_jobs', to='accounts.customer'),
        ),
    ]
