# Generated by Django 4.2.11 on 2026-06-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_scheduled_trips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
