# Generated by Django 4.2.30 on 2026-06-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_backfill_vertical_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_digits',
            field=models.CharField(blank=True, db_index=True, default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='customeremailsuppression',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deliveryjob',
            name='business_type',
            field=models.CharField(blank=True, default='restaurant', max_length=40),
        ),
        migrations.AlterField(
            model_name='deliveryjob',
            name='delivery_commission_rate_applied',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
    ]
