# Generated by Django 4.2.30 on 2026-06-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_field_option_hygiene'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.BigIntegerField(db_index=True, help_text='FK to accounts.Customer (loose — no FK constraint for cross-schema safety).')),
                ('type', models.CharField(blank=True, db_index=True, max_length=40)),
                ('vertical', models.CharField(choices=[('food', 'Food'), ('shops', 'Shops'), ('pharmacy', 'Pharmacy'), ('ride', 'Ride'), ('courier', 'Courier'), ('wallet', 'Wallet'), ('general', 'General')], db_index=True, default='general', max_length=12)),
                ('title', models.CharField(max_length=160)),
                ('body', models.CharField(blank=True, max_length=400)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['customer_id', 'created_at'], name='custnotif_cust_created'), models.Index(fields=['customer_id', 'read_at'], name='custnotif_cust_read')],
            },
        ),
    ]
