# Generated by Django 4.2.30 on 2026-06-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_notification_inbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='recipient_track_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=43),
        ),
    ]
