# Generated by Django 4.2.30 on 2026-06-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_riderequest_recipient_track_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='package_handover_milestone',
            field=models.BooleanField(default=False, help_text="Opt-in: show the distinct sender-side 'collected / handed to courier' package milestone and package-specific (non-ride) status vocabulary. Off preserves today's collapsed 'picked up' labelling."),
        ),
    ]
