# Generated by Django 4.2.30 on 2026-06-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_package_handover_milestone_optin'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='tip_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
