# Generated by Django 4.2.30 on 2026-06-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_riderequest_tip_amount'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customerorderref',
            index=models.Index(fields=['customer', 'status', '-order_created_at'], name='ordref_cust_status_creat_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryjob',
            index=models.Index(fields=['driver', 'status'], name='deliveryjob_driver_status_idx'),
        ),
        migrations.AddIndex(
            model_name='riderequest',
            index=models.Index(fields=['rider', 'kind', 'status'], name='ridereq_rider_kind_status_idx'),
        ),
    ]
