# Generated by Django 4.2.30 on 2026-07-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_customerorderref_ordref_cust_status_creat_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryjob',
            name='pickup_arrival_notified',
            field=models.BooleanField(default=False),
        ),
    ]
