# Generated by Django 4.2.30 on 2026-07-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_deliveryjob_pickup_arrival_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='driver_rejected_at',
            field=models.DateTimeField(blank=True, help_text="When an admin last rejected this driver's application. Cleared on a later approve.", null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='driver_rejection_reason',
            field=models.CharField(blank=True, default='', help_text='Optional admin-supplied reason shown to the driver when their application is rejected.', max_length=300),
        ),
    ]
