# Generated by Django 4.2.30 on 2026-07-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_customer_driver_rejected_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='User must change their password before continuing (set at staff invite).'),
        ),
    ]
