# Generated by Django 4.2.30 on 2026-08-02 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_outboxmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTenantFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(db_index=True, help_text='FK to tenancy.Tenant (loose — no FK constraint for cross-schema safety).')),
                ('restaurant_name', models.CharField(blank=True, max_length=200)),
                ('restaurant_slug', models.CharField(blank=True, max_length=200)),
                ('vertical', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_follows', to='accounts.customer')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['customer', 'tenant_id'], name='cust_tenant_follow_idx')],
                'unique_together': {('customer', 'tenant_id')},
            },
        ),
    ]
