# Generated by Django 4.2.30 on 2026-08-30 03:15

from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    """GIN index on DeliveryJob.declined_by (JSONB) — backs the driver-poll hot path.

    The driver offers endpoint (accounts/views.py) and the ranked-offer dispatcher
    (accounts/dispatch.py) filter with `declined_by__contains=[driver_id]`. Every
    online driver polls this every 5-15s, so without an index the JSONB containment
    predicate is a full-table scan on this growing public-schema table.

    atomic=False + AddIndexConcurrently: CREATE INDEX CONCURRENTLY builds the index
    without an ACCESS EXCLUSIVE lock, so the deploy migrate step does not block
    reads/writes on a live production table (per backend/MIGRATIONS.md convention
    for hot tables — DeliveryJob is listed there).
    """

    atomic = False

    dependencies = [
        ('accounts', '0070_voucherbatch'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='deliveryjob',
            index=GinIndex(fields=['declined_by'], name='deliveryjob_declined_gin'),
        ),
    ]
