# Generated by Django 4.2.30 on 2026-08-30 04:54

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    """B-tree index on DeliveryJob(status, delivered_at) — backs the earnings-reconcile cron.

    reconcile_driver_earnings (runs ~every 15 min) filters
    status=DELIVERED + driver + driver_payout>0 + delivered_at>=cutoff and orders
    by -delivered_at. The only usable index today is the leading `status`, so the
    query scans every DELIVERED job ever (a terminal, monotonically-growing bucket
    on this public-schema table), then filters the delivered_at window and sorts in
    memory — cost grows linearly forever. This composite index makes it an index
    range scan on the window, already ordered.

    atomic=False + AddIndexConcurrently: CREATE INDEX CONCURRENTLY builds the index
    without an ACCESS EXCLUSIVE lock, so the deploy migrate step does not block
    reads/writes on a live production table (per backend/MIGRATIONS.md convention
    for hot tables — DeliveryJob is listed there). SHARED_APPS ×1 (public schema
    only), the safer of the two concurrent-index cases.
    """

    atomic = False

    dependencies = [
        ('accounts', '0071_deliveryjob_deliveryjob_declined_gin'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='deliveryjob',
            index=models.Index(fields=['status', 'delivered_at'], name='deliveryjob_status_deliv_idx'),
        ),
    ]
