# Generated by Django 4.2.30 on 2026-09-01 22:34

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    """Two public-schema hot-table indexes, built CONCURRENTLY.

    1. wcr_tid_ordernum_unsynced_idx — PARTIAL index on WalletChargeRequest
       (tenant_id, order_number) WHERE status='charged' AND bill_synced=False.
       Backs _sync_charged_request_bills() (menu/views.py), run by OwnerOrderListView
       on EVERY ~15s owner/staff order poll. Only tenant_id was indexed, so the poll
       scanned a tenant's whole (unbounded, mostly already-synced) charge-request
       history and filtered in memory — almost always to return nothing. The partial
       predicate matches the query constants, so the common "nothing to sync" case is
       near-O(1) and the index holds only the tiny not-yet-synced set.

    2. deliveryjob_created_idx — btree on DeliveryJob(-created_at). Backs
       AdminDeliveryJobListView's default order_by("-created_at")[:100] on this growing
       public-schema table (previously a full scan + top-N sort on every load).

    atomic=False + AddIndexConcurrently: CREATE INDEX CONCURRENTLY builds each index
    without an ACCESS EXCLUSIVE lock, so the deploy migrate step does not block
    reads/writes on the live tables (per backend/MIGRATIONS.md). Both WalletChargeRequest
    and DeliveryJob live in the public/shared schema, so this is the safer SHARED_APPS ×1
    build, not the per-tenant migrate loop.
    """

    atomic = False

    dependencies = [
        ('accounts', '0072_deliveryjob_deliveryjob_status_deliv_idx'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='deliveryjob',
            index=models.Index(fields=['-created_at'], name='deliveryjob_created_idx'),
        ),
        AddIndexConcurrently(
            model_name='walletchargerequest',
            index=models.Index(
                condition=models.Q(('bill_synced', False), ('status', 'charged')),
                fields=['tenant_id', 'order_number'],
                name='wcr_tid_ordernum_unsynced_idx',
            ),
        ),
    ]
