# Generated by Django 4.2.30 on 2026-10-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0073_deliveryjob_deliveryjob_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderref',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
