from django.urls import include, path
from rest_framework import routers

from accounts.views import (
    ActivationView,
    AdminCreateDeliveryJobView,
    AdminDeliveryJobListView,
    AdminDeliveryZoneDetailView,
    AdminDeliveryZoneListCreateView,
    AdminDriverEarningsView,
    AdminDriverListView,
    AdminDriverApprovalView,
    DriverEarningsView,
    DriverDeliveriesView,
    AdminFlashSaleDetailView,
    AdminPlatformAnalyticsView,
    AdminFlashSaleListCreateView,
    AdminCustomerCreditView,
    AdminCustomerDetailView,
    AdminCustomerListView,
    AdminCustomerOrdersView,
    AdminFundTenantView,
    AdminPlatformSettingsView,
    AdminWalletBonusView,
    AdminWalletVoucherView,
    CustomerWalletRedeemVoucherView,
    CustomerWalletTransferView,
    CustomerEmailRequestView,
    CustomerEmailVerifyView,
    CustomerProfileUpdateView,
    CustomerGoogleAuthView,
    CustomerMarketplaceOrdersView,
    CustomerOrdersView,
    CustomerPhoneRequestView,
    CustomerPhoneVerifyView,
    CustomerSessionView,
    CustomerWalletPayTokenView,
    CustomerWalletChargeRequestsView,
    CustomerWalletChargeApproveView,
    CustomerWalletChargeDeclineView,
    CustomerPushVapidKeyView,
    CustomerPushSubscribeView,
    CustomerWalletView,
    CustomerSavedAddressListCreateView,
    CustomerSavedAddressDeleteView,
    DeliveryRatingView,
    DirectoryView,
    DriverJobAcceptView,
    DriverJobListView,
    DriverJobStatusUpdateView,
    DriverPositionUpdateView,
    DriverRegisterView,
    DriverStatusView,
    MarketplaceView,
    MarketplaceMenuView,
    MarketplacePlaceOrderView,
    MarketplaceOrderStatusView,
    MarketplaceOrderCancelView,
    OrderTrackingView,
    LoginView,
    LogoutView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
    SessionView,
)
from config.api import health_view
from menu.views import AdminWalletListView, AnalyticsEventIngestView
from sales.views import (
    AdminReservationAlertsView,
    AdminPlanFeatureFlagListView,
    AdminPlanFeatureFlagUpdateView,
    AdminTenantLifecycleView,
    AdminTenantListView,
    AdminTenantSettingsExportView,
    AdminTenantSettingsImportView,
    AdminTenantTimelineView,
    AdminTierUpgradeRequestDecisionView,
    AdminTierUpgradeRequestListView,
    AdminAuditLogViewSet,
    LeadOnboardingPackageView,
    LeadProvisionPreviewView,
    LeadResendActivationView,
    LeadViewSet,
    ProvisionLeadViewSet,
    ProvisioningJobViewSet,
)

shared_api_router = routers.DefaultRouter()
shared_api_router.register(r"leads", LeadViewSet, basename="lead")
shared_api_router.register(r"lead-provision", ProvisionLeadViewSet, basename="lead-provision")
shared_api_router.register(r"provision-jobs", ProvisioningJobViewSet, basename="provision-jobs")
shared_api_router.register(r"admin-audit-logs", AdminAuditLogViewSet, basename="admin-audit-logs")

shared_api_urlpatterns = [
    path("api/health/", health_view, name="health"),
    path("api/activate/", ActivationView.as_view(), name="activate"),
    path("api/login/", LoginView.as_view(), name="login"),
    path("api/logout/", LogoutView.as_view(), name="logout"),
    path("api/session/", SessionView.as_view(), name="session"),
    path("api/password-reset/request/", PasswordResetRequestView.as_view(), name="password-reset-request"),
    path("api/password-reset/confirm/", PasswordResetConfirmView.as_view(), name="password-reset-confirm"),
    path("api/analytics/events/", AnalyticsEventIngestView.as_view(), name="analytics-events"),
    path("api/customer/session/", CustomerSessionView.as_view(), name="customer-session"),
    path("api/customer/auth/phone/request/", CustomerPhoneRequestView.as_view(), name="customer-phone-request"),
    path("api/customer/auth/phone/verify/", CustomerPhoneVerifyView.as_view(), name="customer-phone-verify"),
    path("api/customer/auth/google/", CustomerGoogleAuthView.as_view(), name="customer-google-auth"),
    path("api/customer/auth/email/request/", CustomerEmailRequestView.as_view(), name="customer-email-request"),
    path("api/customer/auth/email/verify/", CustomerEmailVerifyView.as_view(), name="customer-email-verify"),
    path("api/customer/orders/", CustomerOrdersView.as_view(), name="customer-orders"),
    path("api/customer/orders/all/", CustomerMarketplaceOrdersView.as_view(), name="customer-orders-all"),
    path("api/customer/profile/", CustomerProfileUpdateView.as_view(), name="customer-profile-update"),
    path("api/customer/wallet/", CustomerWalletView.as_view(), name="customer-wallet"),
    path("api/customer/addresses/", CustomerSavedAddressListCreateView.as_view(), name="customer-addresses"),
    path("api/customer/addresses/<int:address_id>/", CustomerSavedAddressDeleteView.as_view(), name="customer-address-delete"),
    path("api/directory/", DirectoryView.as_view(), name="directory"),
    path("api/marketplace/", MarketplaceView.as_view(), name="marketplace"),
    path("api/marketplace/menu/<slug:slug>/", MarketplaceMenuView.as_view(), name="marketplace-menu"),
    path("api/marketplace/order/", MarketplacePlaceOrderView.as_view(), name="marketplace-order"),
    path("api/marketplace/order/<str:order_number>/cancel/", MarketplaceOrderCancelView.as_view(), name="marketplace-order-cancel"),
    path("api/marketplace/order/<str:order_number>/", MarketplaceOrderStatusView.as_view(), name="marketplace-order-status"),
    path("api/admin/customers/", AdminCustomerListView.as_view(), name="admin-customers"),
    path("api/admin/customers/<int:customer_id>/", AdminCustomerDetailView.as_view(), name="admin-customer-detail"),
    path("api/admin/customers/<int:customer_id>/credit/", AdminCustomerCreditView.as_view(), name="admin-customer-credit"),
    path("api/admin/customers/<int:customer_id>/orders/", AdminCustomerOrdersView.as_view(), name="admin-customer-orders"),
    path("api/admin/wallet/bonus/", AdminWalletBonusView.as_view(), name="admin-wallet-bonus"),
    path("api/admin/wallet/fund-tenant/", AdminFundTenantView.as_view(), name="admin-wallet-fund-tenant"),
    path("api/admin/settings/", AdminPlatformSettingsView.as_view(), name="admin-platform-settings"),
    path("api/admin/wallets/", AdminWalletListView.as_view(), name="admin-wallets"),
    path("api/admin/wallet/vouchers/", AdminWalletVoucherView.as_view(), name="admin-wallet-vouchers"),
    path("api/customer/wallet/pay-token/", CustomerWalletPayTokenView.as_view(), name="customer-wallet-pay-token"),
    path("api/customer/wallet/charge-requests/", CustomerWalletChargeRequestsView.as_view(), name="customer-wallet-charge-requests"),
    path("api/customer/wallet/charge-requests/<int:request_id>/approve/", CustomerWalletChargeApproveView.as_view(), name="customer-wallet-charge-approve"),
    path("api/customer/wallet/charge-requests/<int:request_id>/decline/", CustomerWalletChargeDeclineView.as_view(), name="customer-wallet-charge-decline"),
    path("api/customer/push-vapid-key/", CustomerPushVapidKeyView.as_view(), name="customer-push-vapid-key"),
    path("api/customer/push-subscribe/", CustomerPushSubscribeView.as_view(), name="customer-push-subscribe"),
    path("api/customer/wallet/redeem-voucher/", CustomerWalletRedeemVoucherView.as_view(), name="customer-wallet-redeem-voucher"),
    path("api/customer/wallet/transfer/", CustomerWalletTransferView.as_view(), name="customer-wallet-transfer"),
    path("api/admin/flash-sales/", AdminFlashSaleListCreateView.as_view(), name="admin-flash-sales"),
    path("api/admin/flash-sales/<int:fs_id>/", AdminFlashSaleDetailView.as_view(), name="admin-flash-sale-detail"),
    path("api/admin/delivery-zones/", AdminDeliveryZoneListCreateView.as_view(), name="admin-delivery-zones"),
    path("api/admin/delivery-zones/<int:zone_id>/", AdminDeliveryZoneDetailView.as_view(), name="admin-delivery-zone-detail"),
    path("api/admin/drivers/", AdminDriverListView.as_view(), name="admin-drivers"),
    path("api/admin/drivers/<int:driver_id>/earnings/", AdminDriverEarningsView.as_view(), name="admin-driver-earnings"),
    path("api/admin/drivers/<int:driver_id>/payout/", AdminDriverEarningsView.as_view(), name="admin-driver-payout"),
    path("api/admin/drivers/<int:driver_id>/approve/", AdminDriverApprovalView.as_view(), name="admin-driver-approve"),
    path("api/admin/drivers/<int:driver_id>/reject/", AdminDriverApprovalView.as_view(), name="admin-driver-reject"),
    path("api/admin/platform-analytics/", AdminPlatformAnalyticsView.as_view(), name="admin-platform-analytics"),
    path("api/admin/delivery-jobs/", AdminDeliveryJobListView.as_view(), name="admin-delivery-jobs"),
    path("api/admin/delivery-jobs/create/", AdminCreateDeliveryJobView.as_view(), name="admin-delivery-job-create"),
    path("api/driver/register/", DriverRegisterView.as_view(), name="driver-register"),
    path("api/driver/status/", DriverStatusView.as_view(), name="driver-status"),
    path("api/driver/position/", DriverPositionUpdateView.as_view(), name="driver-position"),
    path("api/driver/earnings/", DriverEarningsView.as_view(), name="driver-earnings"),
    path("api/driver/deliveries/", DriverDeliveriesView.as_view(), name="driver-deliveries"),
    path("api/driver/jobs/", DriverJobListView.as_view(), name="driver-jobs"),
    path("api/driver/jobs/<int:job_id>/accept/", DriverJobAcceptView.as_view(), name="driver-job-accept"),
    path("api/driver/jobs/<int:job_id>/status/", DriverJobStatusUpdateView.as_view(), name="driver-job-status"),
    path("api/marketplace/track/<str:order_number>/", OrderTrackingView.as_view(), name="marketplace-track"),
    path("api/marketplace/track/<str:order_number>/rate/", DeliveryRatingView.as_view(), name="marketplace-track-rate"),
    path("api/lead-provision-preview/<int:lead_id>/", LeadProvisionPreviewView.as_view(), name="lead-provision-preview"),
    path("api/lead-resend-activation/<int:lead_id>/", LeadResendActivationView.as_view(), name="lead-resend-activation"),
    path("api/lead-onboarding-package/<int:lead_id>/", LeadOnboardingPackageView.as_view(), name="lead-onboarding-package"),
    path("api/admin-reservation-alerts/", AdminReservationAlertsView.as_view(), name="admin-reservation-alerts"),
    path("api/admin-plan-feature-flags/", AdminPlanFeatureFlagListView.as_view(), name="admin-plan-feature-flags"),
    path(
        "api/admin-plan-feature-flags/<str:plan_code>/",
        AdminPlanFeatureFlagUpdateView.as_view(),
        name="admin-plan-feature-flags-update",
    ),
    path("api/admin-tenants/", AdminTenantListView.as_view(), name="admin-tenants"),
    path("api/admin-tenants/<int:tenant_id>/lifecycle/", AdminTenantLifecycleView.as_view(), name="admin-tenant-lifecycle"),
    path("api/admin-tenants/<int:tenant_id>/timeline/", AdminTenantTimelineView.as_view(), name="admin-tenant-timeline"),
    path(
        "api/admin-tenants/<int:tenant_id>/settings-export/",
        AdminTenantSettingsExportView.as_view(),
        name="admin-tenant-settings-export",
    ),
    path(
        "api/admin-tenants/<int:tenant_id>/settings-import/",
        AdminTenantSettingsImportView.as_view(),
        name="admin-tenant-settings-import",
    ),
    path(
        "api/admin-tier-upgrade-requests/",
        AdminTierUpgradeRequestListView.as_view(),
        name="admin-tier-upgrade-requests",
    ),
    path(
        "api/admin-tier-upgrade-requests/<int:request_id>/decision/",
        AdminTierUpgradeRequestDecisionView.as_view(),
        name="admin-tier-upgrade-request-decision",
    ),
    path("api/", include(shared_api_router.urls)),
]
