from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework import routers

from accounts.views import (
    OwnerDeliveryRadiusUpdateView,
    OwnerDeliveryZoneView,
    OwnerFlashSaleListView,
    OwnerFlashSaleOptInView,
    OwnerStaffDeleteView,
    OwnerStaffListCreateView,
    StaffChangePasswordView,
    RepairTenantLinkView,
)
from config.shared_api_urls import shared_api_urlpatterns
from menu.chat_views import StaffChatView
from menu.waiter_views import (
    OwnerWaiterCallAcknowledgeView,
    OwnerWaiterCallListView,
    WaiterCallCreateView,
)
from menu.views import (
    AnalyticsSummaryView,
    OwnerCampaignView,
    CategoryViewSet,
    CheckoutIntentView,
    CurrencyRateListView,
    CustomerOrderRateView,
    CustomerOrdersByPhoneView,
    CustomerOrderStatusView,
    CustomerOrderCancelView,
    CustomerOrderPayWalletView,
    DishBulkAvailabilityResetView,
    DishBulkPriceUpdateView,
    OwnerOrderBulkStatusView,
    DishOptionViewSet,
    DishViewSet,
    HappyHourViewSet,
    OptionGroupViewSet,
    OrderHandoffView,
    OwnerAnalyticsExportView,
    OwnerClosureDateDeleteView,
    OwnerClosureDateListCreateView,
    OwnerCommissionStatementView,
    OwnerDataExportView,
    OwnerInvoiceView,
    OwnerCustomerRatingView,
    OwnerPromotionDetailView,
    OwnerPromotionListCreateView,
    OwnerOrderDetailView,
    OwnerOrderExportView,
    OwnerOrderListView,
    OwnerZReportView,
    OwnerNotificationsView,
    OwnerDriverCashoutLookupView,
    OwnerDriverCashoutConfirmView,
    OwnerDeliveryJobActionView,
    OwnerDeliveryTrackView,
    OwnerOrderMarkPaidView,
    OwnerOrderStatusUpdateView,
    OwnerSectionListCreateView,
    OwnerSectionDetailView,
    OwnerRatingListView,
    OwnerRatingReplyView,
    OwnerBestSellersView,
    OwnerCustomerListView,
    OwnerCustomerNotesView,
    OwnerCustomerLoyaltyGrantView,
    OwnerLoyaltyView,
    OwnerMenuImportView,
    ApplyTemplateView,
    OwnerWalletTopupView,
    OwnerWalletResolveTokenView,
    OwnerWalletChargeView,
    OwnerWalletChargeRequestStatusView,
    OwnerWalletHistoryView,
    OwnerWalletFloatView,
    OwnerRevenueChartView,
    OwnerPushSubscribeView,
    OwnerPushVapidKeyView,
    OwnerWaitlistView,
    PlaceOrderView,
    OrderEligibilityView,
    PromoCodeCheckView,
    CustomerLoyaltyRedeemView,
    CustomerLoyaltyConfigView,
    SlotAvailabilityView,
    StaffOrderListView,
    StaffOrderItemReadyView,
    StaffAppendOrderItemsView,
    StaffVoidOrderItemView,
    StaffFireCourseView,
    StaffBulkReadyView,
    StaffTableListView,
    StaffTableStatusView,
    StaffTransferItemsView,
    StaffMergeOrdersView,
    StaffOrderPaymentView,
    StaffPaymentMethodCorrectionView,
    StaffShiftSummaryView,
    SuperCategoryViewSet,
    TableBulkGenerateView,
    TableContextView,
    TableLinkViewSet,
    WaitlistJoinView,
)
from sales.views import (
    OwnerDashboardView,
    OwnerReservationDetailView,
    OwnerReservationExportView,
    OwnerReservationBulkReminderView,
    OwnerReservationBulkStatusView,
    OwnerReservationReminderView,
    OwnerReservationReminderResultView,
    OwnerReservationBulkReminderResultView,
    OwnerReservationTimelineView,
    OwnerReservationListView,
    TierUpgradeTargetsView,
    TierUpgradeRequestListCreateView,
)
from tenancy.api import AppManifestView, ImageDeleteView, ImageUploadView, OwnerDeletionRequestView, ProfileView, TenantMetaView, TranslateView

tenant_router = routers.DefaultRouter()
tenant_router.register(r"super-categories", SuperCategoryViewSet, basename="super-category")
tenant_router.register(r"categories", CategoryViewSet, basename="category")
tenant_router.register(r"dishes", DishViewSet, basename="dish")
tenant_router.register(r"dish-options", DishOptionViewSet, basename="dish-option")
tenant_router.register(r"option-groups", OptionGroupViewSet, basename="option-group")
tenant_router.register(r"tables", TableLinkViewSet, basename="table-link")
tenant_router.register(r"happy-hours", HappyHourViewSet, basename="happy-hour")

urlpatterns = [
    *shared_api_urlpatterns,
    path("api/meta/", TenantMetaView.as_view(), name="tenant-meta"),
    path("app-manifest.json", AppManifestView.as_view(), name="app-manifest"),
    path("api/profile/", ProfileView.as_view(), name="tenant-profile"),
    path("api/uploads/image/", ImageUploadView.as_view(), name="image-upload"),
    path("api/uploads/image-delete/", ImageDeleteView.as_view(), name="image-delete"),
    path("api/translate/", TranslateView.as_view(), name="translate"),
    path("api/order-handoff/", OrderHandoffView.as_view(), name="order-handoff"),
    path("api/checkout-intent/", CheckoutIntentView.as_view(), name="checkout-intent"),
    path("api/place-order/", PlaceOrderView.as_view(), name="place-order"),
    path("api/order-eligibility/", OrderEligibilityView.as_view(), name="order-eligibility"),
    path("api/order-status/<str:order_number>/", CustomerOrderStatusView.as_view(), name="order-status"),
    path("api/order-status/<str:order_number>/cancel/", CustomerOrderCancelView.as_view(), name="order-cancel"),
    path("api/orders/by-phone/", CustomerOrdersByPhoneView.as_view(), name="orders-by-phone"),
    path("api/waiter-call/", WaiterCallCreateView.as_view(), name="waiter-call"),
    path("api/owner/waiter-calls/", OwnerWaiterCallListView.as_view(), name="owner-waiter-calls"),
    path("api/owner/waiter-calls/<int:call_id>/acknowledge/", OwnerWaiterCallAcknowledgeView.as_view(), name="owner-waiter-call-ack"),
    path("api/owner/chat/", StaffChatView.as_view(), name="owner-staff-chat"),
    path("api/orders/<str:order_number>/rate/", CustomerOrderRateView.as_view(), name="order-rate"),
    path("api/orders/<str:order_number>/pay-wallet/", CustomerOrderPayWalletView.as_view(), name="order-pay-wallet"),
    path("api/owner/ratings/", OwnerRatingListView.as_view(), name="owner-ratings"),
    path("api/owner/ratings/<int:pk>/reply/", OwnerRatingReplyView.as_view(), name="owner-rating-reply"),
    path("api/owner/campaigns/", OwnerCampaignView.as_view(), name="owner-campaigns"),
    path("api/owner/closure-dates/", OwnerClosureDateListCreateView.as_view(), name="owner-closure-dates"),
    path("api/owner/closure-dates/<int:closure_id>/", OwnerClosureDateDeleteView.as_view(), name="owner-closure-date-delete"),
    path("api/staff/orders/", StaffOrderListView.as_view(), name="staff-orders"),
    path("api/staff/order-items/<int:item_id>/ready/", StaffOrderItemReadyView.as_view(), name="staff-order-item-ready"),
    path("api/staff/orders/<int:order_id>/items/", StaffAppendOrderItemsView.as_view(), name="staff-order-items-append"),
    path("api/staff/orders/<int:order_id>/items/<int:item_id>/void/", StaffVoidOrderItemView.as_view(), name="staff-order-item-void"),
    path("api/staff/orders/<int:order_id>/items/ready-all/", StaffBulkReadyView.as_view(), name="staff-order-items-ready-all"),
    path("api/staff/orders/<int:order_id>/fire-course/", StaffFireCourseView.as_view(), name="staff-order-fire-course"),
    path("api/staff/orders/<int:order_id>/payments/", StaffOrderPaymentView.as_view(), name="staff-order-payments"),
    path("api/staff/orders/<int:order_id>/payments/<int:payment_id>/correct-method/", StaffPaymentMethodCorrectionView.as_view(), name="staff-payment-correct-method"),
    path("api/staff/tables/", StaffTableListView.as_view(), name="staff-tables"),
    path("api/staff/tables/<int:table_id>/status/", StaffTableStatusView.as_view(), name="staff-table-status"),
    path("api/staff/orders/<int:src_order_id>/transfer-items/", StaffTransferItemsView.as_view(), name="staff-order-transfer-items"),
    path("api/staff/orders/<int:dest_order_id>/merge/", StaffMergeOrdersView.as_view(), name="staff-order-merge"),
    path("api/staff/shift-summary/", StaffShiftSummaryView.as_view(), name="staff-shift-summary"),
    path("api/staff/change-password/", StaffChangePasswordView.as_view(), name="staff-change-password"),
    path("api/owner/z-report/", OwnerZReportView.as_view(), name="owner-z-report"),
    path("api/owner/z-report.csv", OwnerZReportView.as_view(), name="owner-z-report-csv"),
    path("api/owner/orders/", OwnerOrderListView.as_view(), name="owner-orders"),
    path("api/owner/orders/bulk-status/", OwnerOrderBulkStatusView.as_view(), name="owner-orders-bulk-status"),
    path("api/owner/orders/export/", OwnerOrderExportView.as_view(), name="owner-orders-export"),
    path("api/owner/notifications/", OwnerNotificationsView.as_view(), name="owner-notifications"),
    path("api/owner/driver-cashout/", OwnerDriverCashoutLookupView.as_view(), name="owner-driver-cashout-lookup"),
    path("api/owner/driver-cashout/confirm/", OwnerDriverCashoutConfirmView.as_view(), name="owner-driver-cashout-confirm"),
    path("api/owner/orders/<int:order_id>/", OwnerOrderDetailView.as_view(), name="owner-order-detail"),
    path("api/owner/orders/<int:order_id>/status/", OwnerOrderStatusUpdateView.as_view(), name="owner-order-status"),
    path("api/owner/orders/<int:order_id>/delivery-action/", OwnerDeliveryJobActionView.as_view(), name="owner-delivery-action"),
    path("api/owner/orders/<int:order_id>/delivery-track/", OwnerDeliveryTrackView.as_view(), name="owner-delivery-track"),
    path("api/owner/orders/<int:order_id>/mark-paid/", OwnerOrderMarkPaidView.as_view(), name="owner-order-mark-paid"),
    path("api/owner/orders/<int:order_id>/customer-rating/", OwnerCustomerRatingView.as_view(), name="owner-order-customer-rating"),
    path("api/owner/sections/", OwnerSectionListCreateView.as_view(), name="owner-sections"),
    path("api/owner/sections/<int:section_id>/", OwnerSectionDetailView.as_view(), name="owner-section-detail"),
    path("api/owner/promotions/", OwnerPromotionListCreateView.as_view(), name="owner-promotions"),
    path("api/owner/promotions/<int:promo_id>/", OwnerPromotionDetailView.as_view(), name="owner-promotion-detail"),
    path("api/owner/dishes/reset-availability/", DishBulkAvailabilityResetView.as_view(), name="owner-dishes-reset-availability"),
    path("api/owner/dishes/bulk-price/", DishBulkPriceUpdateView.as_view(), name="owner-dishes-bulk-price"),
    path("api/analytics/summary/", AnalyticsSummaryView.as_view(), name="analytics-summary"),
    path("api/owner/analytics/export/", OwnerAnalyticsExportView.as_view(), name="owner-analytics-export"),
    path("api/owner/data-export/", OwnerDataExportView.as_view(), name="owner-data-export"),
    path("api/owner/invoice/", OwnerInvoiceView.as_view(), name="owner-invoice"),
    path("api/owner/commission-statement/", OwnerCommissionStatementView.as_view(), name="owner-commission-statement"),
    path("api/owner/deletion-request/", OwnerDeletionRequestView.as_view(), name="owner-deletion-request"),
    path("api/table-context/<slug:table_slug>/", TableContextView.as_view(), name="table-context"),
    path("api/tables/bulk-generate/", TableBulkGenerateView.as_view(), name="table-bulk-generate"),
    path("api/owner/reservations/", OwnerReservationListView.as_view(), name="owner-reservations"),
    path("api/owner/dashboard/", OwnerDashboardView.as_view(), name="owner-dashboard"),
    path("api/owner/reservations/export/", OwnerReservationExportView.as_view(), name="owner-reservations-export"),
    path("api/owner/reservations/bulk-reminder/", OwnerReservationBulkReminderView.as_view(), name="owner-reservations-bulk-reminder"),
    path("api/owner/reservations/bulk-reminder-result/", OwnerReservationBulkReminderResultView.as_view(), name="owner-reservations-bulk-reminder-result"),
    path("api/owner/reservations/bulk-status/", OwnerReservationBulkStatusView.as_view(), name="owner-reservations-bulk-status"),
    path("api/owner/reservations/<int:lead_id>/reminder/", OwnerReservationReminderView.as_view(), name="owner-reservation-reminder"),
    path("api/owner/reservations/<int:lead_id>/reminder-result/", OwnerReservationReminderResultView.as_view(), name="owner-reservation-reminder-result"),
    path("api/owner/reservations/<int:lead_id>/timeline/", OwnerReservationTimelineView.as_view(), name="owner-reservation-timeline"),
    path("api/owner/reservations/<int:lead_id>/", OwnerReservationDetailView.as_view(), name="owner-reservation-detail"),
    path("api/availability/", SlotAvailabilityView.as_view(), name="slot-availability"),
    path("api/waitlist/", WaitlistJoinView.as_view(), name="waitlist-join"),
    path("api/owner/waitlist/", OwnerWaitlistView.as_view(), name="owner-waitlist"),
    path("api/tier-upgrade-targets/", TierUpgradeTargetsView.as_view(), name="tier-upgrade-targets"),
    path("api/tier-upgrade-requests/", TierUpgradeRequestListCreateView.as_view(), name="tier-upgrade-requests"),
    path("api/repair-tenant-link/", RepairTenantLinkView.as_view(), name="repair-tenant-link"),
    path("api/owner/staff/", OwnerStaffListCreateView.as_view(), name="owner-staff-list"),
    path("api/owner/staff/<int:staff_id>/", OwnerStaffDeleteView.as_view(), name="owner-staff-delete"),
    path("api/owner/flash-sales/", OwnerFlashSaleListView.as_view(), name="owner-flash-sales"),
    path("api/owner/flash-sales/<int:fs_id>/opt-in/", OwnerFlashSaleOptInView.as_view(), name="owner-flash-sale-opt-in"),
    path("api/owner/delivery-zone/", OwnerDeliveryZoneView.as_view(), name="owner-delivery-zone"),
    path("api/owner/delivery-radius/", OwnerDeliveryRadiusUpdateView.as_view(), name="owner-delivery-radius"),
    path("api/owner/push-vapid-key/", OwnerPushVapidKeyView.as_view(), name="owner-push-vapid-key"),
    path("api/owner/push-subscribe/", OwnerPushSubscribeView.as_view(), name="owner-push-subscribe"),
    path("api/owner/customers/", OwnerCustomerListView.as_view(), name="owner-customers"),
    path("api/owner/customers/<int:customer_id>/notes/", OwnerCustomerNotesView.as_view(), name="owner-customer-notes"),
    path("api/owner/customers/<int:customer_id>/loyalty-grant/", OwnerCustomerLoyaltyGrantView.as_view(), name="owner-customer-loyalty-grant"),
    path("api/owner/revenue-chart/", OwnerRevenueChartView.as_view(), name="owner-revenue-chart"),
    path("api/owner/best-sellers/", OwnerBestSellersView.as_view(), name="owner-best-sellers"),
    path("api/promo-code-check/", PromoCodeCheckView.as_view(), name="promo-code-check"),
    path("api/owner/loyalty/", OwnerLoyaltyView.as_view(), name="owner-loyalty"),
    path("api/owner/menu/import/", OwnerMenuImportView.as_view(), name="owner-menu-import"),
    path("api/owner/apply-template/", ApplyTemplateView.as_view(), name="owner-apply-template"),
    path("api/owner/wallet/topup/", OwnerWalletTopupView.as_view(), name="owner-wallet-topup"),
    path("api/owner/wallet/resolve-token/", OwnerWalletResolveTokenView.as_view(), name="owner-wallet-resolve-token"),
    path("api/owner/wallet/charge/", OwnerWalletChargeView.as_view(), name="owner-wallet-charge"),
    path("api/owner/wallet/charge-request/<int:request_id>/", OwnerWalletChargeRequestStatusView.as_view(), name="owner-wallet-charge-request"),
    path("api/owner/wallet/history/<int:customer_id>/", OwnerWalletHistoryView.as_view(), name="owner-wallet-history"),
    path("api/owner/wallet/float/", OwnerWalletFloatView.as_view(), name="owner-wallet-float"),
    path("api/customer/loyalty/config/", CustomerLoyaltyConfigView.as_view(), name="customer-loyalty-config"),
    path("api/customer/loyalty/redeem/", CustomerLoyaltyRedeemView.as_view(), name="customer-loyalty-redeem"),
    path("api/currency-rates/", CurrencyRateListView.as_view(), name="currency-rates"),
    path("api/", include(tenant_router.urls)),
    path(settings.ADMIN_URL_PREFIX, admin.site.urls),
]

if settings.DEBUG:
    # The DRF browsable API login/logout is only needed during development.
    urlpatterns += [path("api-auth/", include("rest_framework.urls"))]

if settings.DEBUG:
    # In development, Django serves media directly (no nginx volume mount).
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# In production, media is served by nginx directly from the shared Docker volume
# (media_data mounted at /app/media in the frontend container).  Django does not
# need a /media/ route — nginx handles it before the request reaches gunicorn.
