http:
  routers:
    kepoli-tenant-wildcard-http:
      entryPoints:
        - http
      rule: HostRegexp(`{tenant:[a-z0-9-]+}.menu.kepoli.com`)
      middlewares:
        - kepoli-tenant-https-redirect
      service: noop@internal

    kepoli-tenant-wildcard-https:
      entryPoints:
        - https
      rule: HostRegexp(`{tenant:[a-z0-9-]+}.menu.kepoli.com`)
      service: menu-kepoli-com-frontend@docker
      priority: 100
      tls: true

  middlewares:
    kepoli-tenant-https-redirect:
      redirectScheme:
        scheme: https
        permanent: true

tls:
  certificates:
    - certFile: /traefik/certs/menu.kepoli.com/fullchain.pem
      keyFile: /traefik/certs/menu.kepoli.com/privkey.pem
