# Generated by Django 4.2.11 on 2026-03-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
