# Generated by Django 4.2.11 on 2026-03-06 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0004_profile_open_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0004_adminauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauditlog',
            name='action',
            field=models.CharField(choices=[('lead_provisioned', 'Lead provisioned'), ('activation_resent', 'Activation resent'), ('onboarding_package_sent', 'Onboarding package sent'), ('tier_upgrade_requested', 'Tier upgrade requested'), ('tier_upgrade_approved', 'Tier upgrade approved'), ('tier_upgrade_rejected', 'Tier upgrade rejected'), ('lead_archived', 'Lead archived'), ('user_role_changed', 'User role changed'), ('tenant_deactivated', 'Tenant deactivated'), ('tenant_reactivated', 'Tenant reactivated')], max_length=64),
        ),
        migrations.CreateModel(
            name='TierUpgradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=20)),
                ('payment_method', models.CharField(default='cash', max_length=24)),
                ('payment_reference', models.CharField(blank=True, max_length=120)),
                ('customer_note', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tier_upgrade_requests', to=settings.AUTH_USER_MODEL)),
                ('current_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tier_upgrade_requests_from', to='tenancy.plan')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tier_upgrade_requests', to=settings.AUTH_USER_MODEL)),
                ('target_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tier_upgrade_requests_to', to='tenancy.plan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_upgrade_requests', to='tenancy.tenant')),
            ],
            options={
                'ordering': ('-requested_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='tierupgraderequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('tenant',), name='unique_pending_tier_upgrade_per_tenant'),
        ),
    ]
