# Generated by Django 4.2.11 on 2026-03-07 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0005_profile_reservation_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0007_reservationtimelineevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp')], default='whatsapp', max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('opened', 'Opened'), ('failed', 'Failed')], db_index=True, default='sent', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True)),
                ('whatsapp_link', models.TextField(blank=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_reminders', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='sales.lead')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_reminders', to='tenancy.tenant')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
