# Generated by Django 4.2.11 on 2026-03-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_reservationreminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauditlog',
            name='action',
            field=models.CharField(choices=[('lead_provisioned', 'Lead provisioned'), ('activation_resent', 'Activation resent'), ('onboarding_package_sent', 'Onboarding package sent'), ('tenant_settings_exported', 'Tenant settings exported'), ('tenant_settings_imported', 'Tenant settings imported'), ('tier_upgrade_requested', 'Tier upgrade requested'), ('tier_upgrade_approved', 'Tier upgrade approved'), ('tier_upgrade_rejected', 'Tier upgrade rejected'), ('lead_archived', 'Lead archived'), ('user_role_changed', 'User role changed'), ('tenant_deactivated', 'Tenant deactivated'), ('tenant_reactivated', 'Tenant reactivated')], max_length=64),
        ),
    ]
