# Generated by Django 4.2.11 on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_lead_tenant_status_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='booked_for',
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text='When the customer wants to come in (date + time combined). Populated on reservation submission.',
            ),
        ),
        migrations.AddField(
            model_name='lead',
            name='party_size',
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                help_text='Number of guests in the reservation.',
            ),
        ),
    ]
