# Generated by Django 4.2.11 on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_lead_booked_for_party_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='reminder_sent_at',
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text='Timestamp of when the pre-reservation reminder was sent to the customer. Null = not yet sent.',
            ),
        ),
    ]
