# Generated by Django 4.2.11 on 2026-06-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_alter_adminauditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('won', 'Won'), ('lost', 'Lost'), ('no_show', 'No-show'), ('paid', 'Paid'), ('provisioning', 'Provisioning'), ('live', 'Live')], default='new', max_length=20),
        ),
    ]
