# Generated by Django 4.2.11 on 2026-06-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='cancel_token',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
