# Generated by Django 4.2.30 on 2026-06-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_alter_adminauditlog_action_add_customer_erased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauditlog',
            name='action',
            field=models.CharField(choices=[('lead_provisioned', 'Lead provisioned'), ('activation_resent', 'Activation resent'), ('onboarding_package_sent', 'Onboarding package sent'), ('tenant_settings_exported', 'Tenant settings exported'), ('tenant_settings_imported', 'Tenant settings imported'), ('tenant_settings_import_dry_run', 'Tenant settings import dry-run'), ('tier_upgrade_requested', 'Tier upgrade requested'), ('tier_upgrade_approved', 'Tier upgrade approved'), ('tier_upgrade_rejected', 'Tier upgrade rejected'), ('lead_archived', 'Lead archived'), ('user_role_changed', 'User role changed'), ('tenant_deactivated', 'Tenant deactivated'), ('tenant_reactivated', 'Tenant reactivated'), ('wallet_bonus_issued', 'Wallet bonus issued'), ('tenant_float_funded', 'Tenant float funded'), ('customer_wallet_credited', 'Customer wallet credited'), ('voucher_issued', 'Wallet voucher issued'), ('driver_approved', 'Driver approved'), ('driver_rejected', 'Driver rejected'), ('driver_payout_recorded', 'Driver payout recorded'), ('platform_settings_updated', 'Platform settings updated'), ('tenant_live_orders_viewed', 'Tenant live orders viewed'), ('customer_pii_viewed', 'Customer PII viewed'), ('customer_driver_toggled', 'Customer driver toggled'), ('delivery_job_created', 'Delivery job created'), ('tenant_deletion_requested', 'Tenant deletion requested'), ('plan_feature_flags_updated', 'Plan feature flags updated'), ('ride_pii_viewed', 'Ride PII viewed'), ('car_docs_viewed', 'Car docs viewed'), ('delivery_job_pii_viewed', 'Delivery job PII viewed'), ('customer_erased', 'Customer PII erased')], max_length=64),
        ),
    ]
