# Generated by Django 4.2.11 on 2026-03-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=48)),
                ('path', models.CharField(blank=True, max_length=320)),
                ('category_slug', models.SlugField(blank=True, max_length=160)),
                ('dish_slug', models.SlugField(blank=True, max_length=210)),
                ('source', models.CharField(blank=True, max_length=48)),
                ('session_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='menu_analyt_event_t_b9e5bd_idx'), models.Index(fields=['category_slug', 'created_at'], name='menu_analyt_categor_689f99_idx'), models.Index(fields=['dish_slug', 'created_at'], name='menu_analyt_dish_sl_42d3ac_idx')],
            },
        ),
    ]
