# Generated by Django 4.2.11 on 2026-03-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_tablelink"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="category",
            name="name_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="dish",
            name="description_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="dish",
            name="name_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="dishoption",
            name="name_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
