# Generated by Django 4.2.11 on 2026-05-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_dish_allergens'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='menu_order_status_7436bc_idx',
            old_name='menu_order_status_created_idx',
        ),
        migrations.AddField(
            model_name='dish',
            name='availability_schedule',
            field=models.JSONField(blank=True, default=None, help_text="Optional time-based availability window. Schema: {days: ['mon','tue',...], time_start: 'HH:MM', time_end: 'HH:MM'}. null = always available. Empty days list = any day.", null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Temporary daily availability. False = sold out (still visible on menu but cannot be ordered). Use is_published=False to permanently hide the dish.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Delivery fee snapshot captured at order placement time.', max_digits=8),
        ),
    ]
