# Generated by Django 4.2.11 on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_add_availability_schedule_to_dish'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosureDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(
                    db_index=True,
                    unique=True,
                    help_text='The calendar date on which the restaurant is closed (YYYY-MM-DD).',
                )),
                ('label', models.CharField(
                    blank=True,
                    max_length=100,
                    help_text="Optional reason / holiday name shown to the owner (e.g. 'Christmas Day').",
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
