# Generated by Django 4.2.11 on 2026-06-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0032_staffmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='handled_by_user_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='accounts.User pk of the staff/owner who last advanced this order.', null=True),
        ),
    ]
