# Generated by Django 4.2.11 on 2026-06-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0033_order_handled_by_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text="When the order's bill was fully settled (paid).", null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], db_index=True, default='unpaid', max_length=12),
        ),
        migrations.AddField(
            model_name='order',
            name='review_prompt_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
