# Generated by Django 4.2.11 on 2026-06-04 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0035_backfill_completed_orders_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('color', models.CharField(blank=True, help_text='Optional hex colour for the floor UI, e.g. #f59e0b.', max_length=9)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('position', 'name', 'id'),
            },
        ),
        migrations.AddField(
            model_name='tablelink',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='menu.tablesection'),
        ),
        migrations.CreateModel(
            name='SectionServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, help_text='accounts.User pk of the assigned waiter.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='menu.tablesection')),
            ],
            options={
                'unique_together': {('section', 'user_id')},
            },
        ),
    ]
