# Generated by Django 4.2.11 on 2026-06-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0036_tablesection_tablelink_section_sectionserver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('out_for_delivery', 'Out for delivery'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
    ]
