# Generated by Django 4.2.11 on 2026-06-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0038_orderitem_is_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the customer wants this advance order fulfilled (null = ASAP). While set and status=SCHEDULED the order is hidden from the kitchen until the release sweep moves it to PENDING shortly before this time.', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('out_for_delivery', 'Out for delivery'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
    ]
