# Generated by Django 4.2.11 on 2026-06-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0039_order_scheduled_for_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='loyalty_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount applied by redeeming loyalty points at checkout.', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='redeemed_loyalty_points',
            field=models.PositiveIntegerField(blank=True, help_text="Loyalty points spent on this order's checkout discount. Null = none redeemed.", null=True),
        ),
    ]
