# Generated by Django 4.2.11 on 2026-06-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0040_order_loyalty_discount_order_redeemed_loyalty_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_code',
            field=models.CharField(blank=True, db_index=True, max_length=12),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_proof_photo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
