# Generated by Django 4.2.11 on 2026-06-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0041_order_delivery_code_order_delivery_proof_photo_url'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'updated_at'], name='menu_order_status_c87a7e_idx'),
        ),
    ]
