# Generated by Django 4.2.11 on 2026-06-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0042_order_menu_order_status_c87a7e_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='owner_reply',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rating',
            name='owner_reply_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
