# Generated by Django 4.2.11 on 2026-06-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0045_dish_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_temporarily_disabled',
            field=models.BooleanField(default=False, help_text='Temporarily hide this category and all its dishes from the customer menu without permanently unpublishing it — useful for mid-service pauses (e.g. a section is sold out for the evening). Set back to False to restore.'),
        ),
    ]
