# Generated by Django 4.2.11 on 2026-06-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0046_category_temporarily_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_voided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='void_reason',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
