# Generated by Django 4.2.11 on 2026-06-11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0047_orderitem_void'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('method', models.CharField(choices=[('wallet', 'Wallet'), ('cash', 'Cash')], max_length=8)),
                ('recorded_by_user_id', models.IntegerField(blank=True, null=True)),
                ('recorded_by_name', models.CharField(blank=True, max_length=80)),
                ('note', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='menu.order')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
