# Generated by Django 4.2.11 on 2026-06-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0053_dish_stock_auto_zeroed'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='course',
            field=models.PositiveSmallIntegerField(default=0, help_text='Course number for dine-in sequencing (0 = no course / fire immediately; 1–4 = starter → main → cheese → dessert). Dishes inherit this at order time.'),
        ),
        migrations.AddField(
            model_name='order',
            name='fired_course',
            field=models.PositiveSmallIntegerField(default=1, help_text='Highest course number that has been fired (sent to kitchen). Items with course <= fired_course are considered fired; items with course > fired_course are held. Course 0 items are always fired immediately. Default 1 means course-1 items fire on placement.'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='course',
            field=models.PositiveSmallIntegerField(default=0, help_text='Course snapshot captured at order placement. 0 = fire immediately; 1–4 = held until Order.fired_course reaches this value.'),
        ),
    ]
