# Generated by Django 4.2.11 on 2026-06-14 17:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0058_ops4_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission_rate_applied',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Snapshot of the commission rate applied (fraction, 0.10 = 10%).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Platform commission for marketplace orders (rate × food subtotal).', max_digits=10),
        ),
    ]
