# Generated by Django 4.2.30 on 2026-06-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0062_order_phone_digits'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Operator-set cost / COGS per unit. Optional. Used to compute food-cost% on the owner dashboard. Leave blank for items whose cost is not tracked.', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone_digits',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
    ]
