# Generated by Django 4.2.30 on 2026-06-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0070_field_option_hygiene'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sla_notified_at',
            field=models.DateTimeField(blank=True, help_text='Stamped when the server-side SLA-escalation push is sent to owner/manager devices for an order left PENDING past Profile.pending_sla_minutes. Null = not yet escalated. Used so each stale order escalates at most once.', null=True),
        ),
    ]
