# Generated by Django 4.2.30 on 2026-06-21 07:48

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0071_order_sla_notified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_by_user_id', models.IntegerField(blank=True, db_index=True, help_text='accounts.User pk of the owner/staff who opened the drawer.', null=True)),
                ('opened_by_name', models.CharField(blank=True, help_text='Display-name snapshot taken at open time.', max_length=150)),
                ('opening_float', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cash placed in the drawer before service begins (float/seed money).', max_digits=10)),
                ('opened_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_index=True, default='open', max_length=8)),
                ('closed_at', models.DateTimeField(blank=True, help_text='When the drawer was closed (blind count submitted).', null=True)),
                ('closed_by_user_id', models.IntegerField(blank=True, help_text='accounts.User pk of the owner/staff who closed the drawer.', null=True)),
                ('closed_by_name', models.CharField(blank=True, max_length=150)),
                ('counted_total', models.DecimalField(blank=True, decimal_places=2, help_text='Physical count entered by the closer (blind — before seeing expected).', max_digits=10, null=True)),
                ('expected_total', models.DecimalField(blank=True, decimal_places=2, help_text='Expected drawer balance computed at close: float + cash sales + pay-ins − pay-outs.', max_digits=10, null=True)),
                ('over_short', models.DecimalField(blank=True, decimal_places=2, help_text='Variance: counted − expected. Positive = overage, negative = shortage.', max_digits=10, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-opened_at',),
            },
        ),
        migrations.CreateModel(
            name='DrawerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pay_in', 'Pay-in'), ('pay_out', 'Pay-out')], db_index=True, max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive value. Direction is determined by ``kind``.', max_digits=10)),
                ('reason', models.CharField(blank=True, help_text="Free-text reason for this cash movement (e.g. 'Milk supplier', 'Petty cash').", max_length=200)),
                ('recorded_by_user_id', models.IntegerField(blank=True, null=True)),
                ('recorded_by_name', models.CharField(blank=True, max_length=150)),
                ('at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='menu.drawersession')),
            ],
            options={
                'ordering': ('at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='drawersession',
            index=models.Index(fields=['status', 'opened_at'], name='menu_drawer_status_opened_idx'),
        ),
    ]
