# Generated by Django 4.2.30 on 2026-06-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0072_cash_drawer_session_and_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='seat',
            field=models.PositiveSmallIntegerField(default=0, help_text='Which seat (cover) ordered this item. 0 = unassigned / one bill. Set by the waiter at placement or append time for split-by-seat billing.'),
        ),
    ]
