# Generated by Django 4.2.30 on 2026-06-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0073_seat_level_ordering'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tablelink',
            index=models.Index(fields=['section', 'slug'], name='tablelink_section_slug_idx'),
        ),
    ]
