# Generated by Django 4.2.30 on 2026-07-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0074_tablelink_tablelink_section_slug_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='comp_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='comped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='comped_by_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_comped',
            field=models.BooleanField(default=False),
        ),
    ]
