# Generated by Django 4.2.30 on 2026-07-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0075_v3_orderitem_comp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_note',
            field=models.CharField(blank=True, default='', help_text="Free-text detail supplied when cancel_reason == 'other'.", max_length=300),
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(blank=True, choices=[('out_of_stock', 'Out of stock'), ('too_busy', 'Too busy'), ('closing_soon', 'Closing soon'), ('item_unavailable', 'Item unavailable'), ('address_issue', 'Address issue'), ('customer_request', 'Customer request'), ('other', 'Other')], default='', help_text='Canned reason code for a staff cancellation. Blank if not staff-cancelled.', max_length=32),
        ),
    ]
