# Generated by Django 4.2.30 on 2026-08-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0076_order_cancel_note_order_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
