export const DEMO_TENANT_META = {
  name: "Kepoli Demo Restaurant",
  slug: "demo",
  profile: {
    restaurant_name: "Kepoli Demo Restaurant",
    tagline: "Fresh menu, fast WhatsApp ordering",
    description: "A public demo that shows the customer menu flow before a real tenant is provisioned.",
    city: "Casablanca",
    address: "Demo experience",
    is_open: true,
    is_menu_published: true,
    is_menu_temporarily_disabled: false,
    google_maps_url: "https://maps.google.com",
    reservation_url: "",
    phone: "+212600000000",
    whatsapp: "+212600000000",
    language: "en",
    instagram_url: "https://instagram.com",
    facebook_url: "https://facebook.com",
    tiktok_url: "https://tiktok.com",
  },
  plan: {
    tier_code: "basic",
    tier_name: "Basic",
    name: "Basic",
    currency: "MAD",
    can_checkout: false,
    can_whatsapp_order: true,
    max_languages: 1,
    is_active: true,
  },
  entitlements: {
    tier_code: "basic",
    tier_name: "Basic",
    ordering_mode: "whatsapp",
    can_order: true,
    can_checkout: false,
    can_whatsapp_order: true,
    max_languages: 1,
    is_active: true,
  },
};

export const DEMO_CATEGORIES = [
  {
    id: 1,
    name: "Breakfast",
    slug: "breakfast",
    description: "Morning favorites and fresh starts.",
    image_url: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80",
    position: 1,
    is_published: true,
    dishes: [
      {
        id: 101,
        category: 1,
        name: "Royal Breakfast",
        slug: "royal-breakfast",
        description: "Eggs, msemen, cheese, olives, honey, and fresh juice.",
        price: 68,
        currency: "MAD",
        image_url: "https://images.unsplash.com/photo-1484723091739-30a097e8f929?auto=format&fit=crop&w=900&q=80",
        position: 1,
        is_published: true,
        options: [
          { id: 1001, dish: 101, name: "Extra cheese", price_delta: 8, is_required: false, max_select: 1 },
          { id: 1002, dish: 101, name: "Orange juice upgrade", price_delta: 10, is_required: false, max_select: 1 },
        ],
      },
      {
        id: 102,
        category: 1,
        name: "Avocado Toast",
        slug: "avocado-toast",
        description: "Sourdough, smashed avocado, herbs, and poached egg.",
        price: 49,
        currency: "MAD",
        image_url: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=900&q=80",
        position: 2,
        is_published: true,
        options: [{ id: 1003, dish: 102, name: "Add salmon", price_delta: 18, is_required: false, max_select: 1 }],
      },
    ],
  },
  {
    id: 2,
    name: "Main dishes",
    slug: "main-dishes",
    description: "Core menu items for lunch and dinner.",
    image_url: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    position: 2,
    is_published: true,
    dishes: [
      {
        id: 201,
        category: 2,
        name: "Chicken Pasta",
        slug: "chicken-pasta",
        description: "Creamy pasta with grilled chicken and parmesan.",
        price: 84,
        currency: "MAD",
        image_url: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=900&q=80",
        position: 1,
        is_published: true,
        options: [
          { id: 2001, dish: 201, name: "Extra parmesan", price_delta: 7, is_required: false, max_select: 1 },
          { id: 2002, dish: 201, name: "Gluten free pasta", price_delta: 12, is_required: false, max_select: 1 },
        ],
      },
      {
        id: 202,
        category: 2,
        name: "Grilled Burger",
        slug: "grilled-burger",
        description: "Beef burger, cheddar, caramelized onion, and house fries.",
        price: 79,
        currency: "MAD",
        image_url: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=80",
        position: 2,
        is_published: true,
        options: [
          { id: 2003, dish: 202, name: "Extra cheese", price_delta: 6, is_required: false, max_select: 1 },
          { id: 2004, dish: 202, name: "Double patty", price_delta: 22, is_required: false, max_select: 1 },
        ],
      },
    ],
  },
  {
    id: 3,
    name: "Desserts",
    slug: "desserts",
    description: "Sweet endings.",
    image_url: "https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=800&q=80",
    position: 3,
    is_published: true,
    dishes: [
      {
        id: 301,
        category: 3,
        name: "Chocolate Cake",
        slug: "chocolate-cake",
        description: "Soft sponge, ganache filling, and cocoa dust.",
        price: 38,
        currency: "MAD",
        image_url: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=900&q=80",
        position: 1,
        is_published: true,
        options: [{ id: 3001, dish: 301, name: "Vanilla ice cream", price_delta: 9, is_required: false, max_select: 1 }],
      },
      {
        id: 302,
        category: 3,
        name: "Seasonal Fruit Bowl",
        slug: "seasonal-fruit-bowl",
        description: "Fresh fruit mix with mint and citrus glaze.",
        price: 32,
        currency: "MAD",
        image_url: "https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?auto=format&fit=crop&w=900&q=80",
        position: 2,
        is_published: true,
        options: [],
      },
    ],
  },
];

export const buildDemoDishesByCategory = () =>
  Object.fromEntries(
    DEMO_CATEGORIES.map((category) => [category.slug, Array.isArray(category.dishes) ? [...category.dishes] : []])
  );
