# Generated by Django 4.2.11 on 2026-05-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0012_profile_receipt_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='menu_theme',
            field=models.CharField(choices=[('dark', 'Dark (default)'), ('light', 'Light'), ('warm', 'Warm')], default='dark', help_text='Visual colour theme for the public-facing menu page.', max_length=20),
        ),
    ]
