# Generated by Django 4.2.11 on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0013_add_menu_theme_to_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sms_notifications_enabled',
            field=models.BooleanField(
                default=False,
                help_text="When enabled, customers receive an SMS when their order status changes to 'ready'. Requires Twilio credentials in environment.",
            ),
        ),
    ]
