# Generated by Django 4.2.11 on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0014_add_sms_notifications_enabled_to_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auto_confirm_reservations',
            field=models.BooleanField(
                default=False,
                help_text='Automatically confirm (status → won) new reservation requests that are far enough in advance.',
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='auto_confirm_min_hours',
            field=models.PositiveSmallIntegerField(
                default=24,
                help_text='Minimum hours in advance a reservation must be booked to qualify for auto-confirm. 0 = always auto-confirm regardless of timing.',
            ),
        ),
    ]
