# Generated by Django 4.2.11 on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0015_add_auto_confirm_reservations_to_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reservation_reminders_enabled',
            field=models.BooleanField(
                default=False,
                help_text="When enabled, customers receive an email (and SMS if configured) ~2 hours before their confirmed reservation.",
            ),
        ),
    ]
