# Generated by Django 4.2.11 on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0016_add_reservation_reminders_enabled_to_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='menu_card_layout',
            field=models.CharField(
                max_length=10,
                choices=[
                    ('row',     'Row (image-right compact card — Wolt/Deliveroo style)'),
                    ('card',    'Card (image-top grid card)'),
                    ('compact', 'Compact (name + price + add button, single line)'),
                ],
                default='row',
                help_text='Controls how dish items appear on the public menu page.',
            ),
        ),
    ]
