# Generated by Django 4.2.11 on 2026-06-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0025_profile_delivery_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vat_label',
            field=models.CharField(blank=True, default='', help_text="Label for the tax line on receipts (e.g. 'VAT', 'TVA'). Defaults to 'VAT' when blank.", max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='VAT/TVA rate as a percentage (e.g. 20.00 = 20%). Menu prices are treated as VAT-inclusive: the charged total is unchanged, and this rate is used only to break the VAT amount out on orders, receipts and invoices. 0 = no VAT line shown.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='delivery_zone_description',
            field=models.CharField(blank=True, help_text="Short description of the delivery area shown to customers (e.g. '5 km radius — city centre only').", max_length=200),
        ),
    ]
