# Generated by Django 4.2.11 on 2026-06-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0026_profile_vat_label_profile_vat_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='float_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
