# Generated by Django 4.2.11 on 2026-06-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0027_tenant_float_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='platform_delivery_enabled',
            field=models.BooleanField(default=False, help_text='When enabled, each delivery order automatically creates a job for the platform driver network. Leave off if the restaurant handles its own delivery.'),
        ),
    ]
