# Generated by Django 4.2.11 on 2026-06-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0030_profile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='delivery_base_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base fee added before the per-km charge in distance-based pricing.', max_digits=8),
        ),
        migrations.AddField(
            model_name='profile',
            name='delivery_free_over',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Order subtotal at or above which delivery is free (0 = never free). Applies to both flat and distance-based pricing.', max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='delivery_per_km',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Per-kilometre delivery rate. 0 = disable distance pricing and use the flat delivery_fee instead.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='profile',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Flat delivery fee. Used as a fallback when distance pricing is not configured (delivery_per_km = 0) or the customer's coordinates are unknown.", max_digits=8),
        ),
    ]
