# Generated by Django 4.2.11 on 2026-06-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0031_profile_delivery_base_fee_profile_delivery_free_over_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['directory_opt_in', 'is_menu_published'], name='profile_marketplace_idx'),
        ),
    ]
