# Generated by Django 4.2.11 on 2026-06-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0032_profile_profile_marketplace_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('cafe', 'Café'), ('bakery', 'Bakery'), ('grocery', 'Grocery'), ('retail', 'Retail / Shop')], default='restaurant', help_text='Vertical this tenant operates in. Gates restaurant-only features (tables, dine-in, waiter, kitchen, reservations) for non-restaurant types.', max_length=20),
        ),
    ]
