# Generated by Django 4.2.11 on 2026-06-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0033_profile_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='delivery_commission_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Platform commission on each delivery fee, as a percentage (0–100). Admin-controlled (owners can't edit it); the driver is paid the fee minus this cut. Default 0 → the driver keeps 100% of the delivery fee.", max_digits=5),
        ),
    ]
