# Generated by Django 4.2.11 on 2026-06-14 17:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0039_profile_service_day_cutover_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='marketplace_commission_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), help_text="Platform take rate on each marketplace order, as a fraction (0.10 = 10%). Admin-controlled (owners can't edit it). Default 0.10.", max_digits=5),
        ),
    ]
