# Generated by Django 4.2.11 on 2026-06-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0040_profile_marketplace_commission_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rating_avg',
            field=models.DecimalField(blank=True, decimal_places=1, help_text="Denormalized average rating (1dp) mirrored from this tenant's menu.Rating rows. Null = no ratings.", max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, help_text="Denormalized count of this tenant's menu.Rating rows."),
        ),
    ]
