# Generated by Django 4.2.11 on 2026-06-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0041_profile_rating_avg_profile_rating_count'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['directory_opt_in', 'is_menu_published', 'rating_avg'], name='profile_marketplace_rate_idx'),
        ),
    ]
