# Generated by Django 4.2.11 on 2026-06-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0042_profile_profile_marketplace_rate_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='marketplace_promos',
            field=models.JSONField(blank=True, default=list, help_text="Denormalized schedule of this tenant's is_active promos for the marketplace promo badge. Each entry: {promo_type, discount_value (str), days, time_start, time_end, active_from (ISO|null), active_until (ISO|null)}. Ordered by highest discount first. 'Live now' is evaluated in-memory at request time."),
        ),
    ]
