# Generated by Django 4.2.30 on 2026-06-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0046_plan_price_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_prep_minutes',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Typical kitchen prep time in minutes, used to quote a pre-order ETA ('Ready in ~X–Y min') on the menu and at checkout. Falls back to the rolling average of recent orders, then to a platform default when blank.", null=True),
        ),
    ]
