# Generated by Django 4.2.30 on 2026-06-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0047_profile_default_prep_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='busy_extra_minutes',
            field=models.PositiveSmallIntegerField(default=0, help_text='Extra minutes added to the quoted ready/ETA while the kitchen is slammed (e.g. +10 / +20). Applied only while busy_extra_until is in the future; 0 = no bump. Additive on top of the normal estimate.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='busy_extra_until',
            field=models.DateTimeField(blank=True, help_text='Time-based expiry for busy_extra_minutes. When this passes the prep bump auto-clears. Null or past = no bump regardless of minutes.', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='orders_paused_until',
            field=models.DateTimeField(blank=True, help_text='When set to a FUTURE time, new online orders are rejected with a clear reason until this moment, then accepting auto-resumes. Null or past = ordering open. Set via the owner Busy-mode control.', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pending_sla_minutes',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Minutes a 'pending' order may wait before the server sends an SLA escalation push to owner/manager devices. Null = platform default.", null=True),
        ),
    ]
