# Generated by Django 4.2.30 on 2026-06-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0048_busy_mode_and_pending_sla'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auto_accept_orders',
            field=models.BooleanField(default=False, help_text='When True, new online (pickup/delivery) orders are auto-confirmed at placement with a quoted prep time instead of requiring a manual Confirm tap. False (default) keeps the manual-confirm flow.'),
        ),
    ]
