# Generated by Django 5.2.17 on 2026-08-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0050_autolist_published_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='delivery_auto_refund_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Minutes a prepaid delivery order may stay stuck pre-pickup before the platform auto-refunds & cancels it. 0 = never auto-refund (the owner resolves every stuck delivery manually).'),
        ),
    ]
