# Generated by Django 4.2.30 on 2026-09-26 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0051_profile_delivery_auto_refund_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='directory_opt_in',
            field=models.BooleanField(default=True, help_text="Show this restaurant in the platform's public marketplace. ON by default (opt-out): a new business is listed once it publishes its menu (the marketplace query also requires is_menu_published=True, so an unpublished/incomplete business never appears prematurely). The owner can opt out by unchecking the directory toggle."),
        ),
    ]
